import { CourseType } from '../types/Courses';

export const getCourses = async (): Promise<CourseType[]> => {
    return [
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Русский Язык',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Длиннофамилова И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Русский Язык',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Длиннофамилова И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Русский Язык',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Длиннофамилова И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Русский Язык',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Длиннофамилова И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Русский Язык',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Длиннофамилова И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
        {
            title: 'Математика',
            startDate: new Date('01.01.2003'),
            endDate: new Date('01.01.2004'),
            teacher: 'Пупкин И.Д.',
            type: 'ЛК',
        },
    ];
};
